audacious-media-player/audacious-plugins

- src/albumart-qt/albumart.cc
1) Depends on my pull request in core libaudqt.
2) Uses const MARGIN to inhibit widget resize on each icon update. (Needs review.)
> albumart-qt: Rewrote to match gtk counterpart behaviour.

- src/statusicon-qt/statusicon.cc
That would be ( or rather was ) the only usability thing standing between "pure" KDE (no gtk) and my favorite player. :smiley:
> statusicon-qt: Enable pause/play toggle with middle click.

- configure.ac
Otherwise it tries to use the flac filewriter when flac isn't available.
Signed-off-by: Gustavo Zacarias <gustavo@zacarias.com.ar>
> configure: use correct logic for flac filewriter

- src/statusicon-qt/statusicon.cc
The commit removes the Hide/Restore toggle in the Qt systray, making the Gtk and Qt menus consistent with each other.
> remove hide/restore toggle in Qt systray

- configure.ac
Hi, I have released version 1.0.0 of Ampache Browser library.  The name of the generated library file is now libampache_browser_1.so instead of libampache_browser_0.so.  This is adaptation configure.ac to reflect that change.  I should have named the library file with _1 suffix right from the start but better late than never.  Sorry for inconvenience.
> Update Ampache Browser library name to version 1.

- src/qtui/info_bar.cc
Fixes "info_bar.cc:258:21: error: no viable overloaded '='"
> qtui: fix build with Qt 5.10

- src/mpris2/plugin.cc
Mpris Track_Id type should be a dbus object path, not a string.
https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Simple-Type:Track_Id
> Make mpris trackid type a dbus object path

- src/psf/peops/spu.cc
- src/psf/peops/spu.h
- src/psf/peops2/spu.cc
- src/psf/peops2/spu.h
- src/psf/plugin.cc
This PR adds an option in the psf plugin to ignore the length of the tracks, resulting in endless looping.
It has been tested with psf and psf2 files. Other plugins have similar options.
> psf: Add ignore length option for endless looping

- src/jack/jack-ng.cc
Currently, the client name used by the JACK audio plugin is hard-coded to "audacious". Therefore, when running multiple instances, using the -1, -2 -,3, etc. options, these cannot be properly distinguished. I've added a config option allowing to set an individual client name for each instance profile. To accommodate to more complex patchbay configurations, setting a custom client name might also be useful when running a single instance.
> JACK client name configurable

- src/jack/jack-ng.cc
To give the advanced user more control over the auto-connect feature of the JACK output plugin, I've added the following options:
- Select specific ports using a regular expression (e.g. "playback_[3,4]" to use the second pair of stereo channels of a multi-channel audio interface instead of the first).
- Allow non-physical ports to be used (like those opened by alsa_out or other processing clients).
- Specify a higher port count (than 2) for the "upmix" feature or set it to 1 to disable it (e.g. a port filter of "playback_[1,2,5,6]" and a channel count of 4 will route mono and stereo inputs to the front and rear channels of a surround sound interface). Of course, this will most likely only give useful results in cases where the port count is a multiple of the input channel count.
- Allow …
> JACK: Additional settings for the auto-connect feature

- src/pulse/pulse_audio.cc
Currently, the context and stream names used by the PulseAudio audio plugin are hard-coded to "Audacious". Therefore, when running multiple instances, using the -1, -2 -,3, etc. options, these cannot be properly distinguished.
I've added a config option allowing to set an individual client name for each instance profile. To accommodate to more complex patchbay configurations, setting a custom client name might also be useful when running a single instance.
My main motivation is to be able to run two (or more) instances of Audacious and map the audio of each instance to a different sound card.
> Making pulse audio configurable

- meson.build
- src/config.h.meson
- src/console/meson.build
- src/psf/meson.build
- src/xsf/meson.build
Meson builds are broken on mingw32 (and potentially other platforms).
> Fixing meson builds on mingw32

- src/adplug/adplug-xmms.cc
When toying a bit more with the adplug MAME renderer, I noted while wearing headphones that the output only came from the left channel. This PR fixes the issue.
> adplug: Fixing MAME renderer to play in both channels

- src/albumart-qt/albumart.cc
Made album art plugin be aware of device pixel ratio for drawing. Note that this can result in pretty small pictures if the album art is smaller than the pixbuf size. It might be worth scaling up pictures by the device pixel ratio for smaller images.
> Add HiDPI support to QT album art plugin

- src/mpg123/mpg123.cc
When the bitrate is CBR a wrong value was showed in song info and in the playlist because it was calculated. Now when the bitrate is CBR the bitrate is obtained from the first frame of libmpg123.
Also now in info is shown if file is CBR, VBR or ABR.
https://redmine.audacious-media-player.org/issues/937
> When bitrate is CBR use bitrate, if not try to calculate it.

- src/qtui/playlist-qt.cc
- src/qtui/playlist-qt.h
This ensures that playback will only occur when a playlist item is double-
clicked, regardless of the user's desktop single-click setting.
> qtui: Use doubleClicked signal instead of activate

- src/notify/notify.cc
- src/notify/osd.cc
The notifications seemed too long for me, and I don't want to change the default setting in the server since sometimes other applications might display more text in there and a longer duration might bew thus necessary to read them. This allows the user to specify their own duration if desired.
The only caveat is that checking both "Always show notification" and "Custom notification duration" will result in the notification always being shown due to how the code is structured, as I can't find a way to uncheck one of the CheckBoxes if the other is already checked. Suggestions welcome.
> notify: Allow specifying a custom notification duration

- src/qtui/time_slider.cc
- src/qtui/time_slider.h
Allows seeking with the mouse wheel by placing the cursor over the
TimeSlider. This feature is already available in GTK mode.
> qtui: Implement wheelEvent for TimeSlider

- src/cdaudio/cdaudio-ng.cc
The freedb.org database of compact track listings has shut down. Any
program functionality that tries to fetch from or submit data to
freedb.org is broken now.
An alternative service is available at gnudb.gnudb.org, see
https://www.gnudb.org/
Fixes https://redmine.audacious-media-player.org/issues/994
> Move from freedb.org to gnudb.gnudb.org

- src/scrobbler2/scrobbler.cc
- src/scrobbler2/scrobbler_communication.cc
The purpose of this PR is to add album artist support to `scrobbler2` plugin, with some additional fixes in functions used for handling scrobble cache file.
The first commit fixes two problems which can happen when the scrobble cache file (`scrobbler.log`) is parsed. In some cases reading incorrectly formatted fields in `scrobbler.log` can cause a segmentation fault (a minimal example is a field containing only three `\t` characters). The other problem is that reading an empty line from scrobble cache stops further cache processing, and causes all subsequent cache entries to be lost. 
This doesn't seem to be a problem in real life usage, because the plugin never creates incorrectly formatted cache entries. I only found these problems when I was feeding various incorrectly formatted cache …
> Implement album artist support in scrobbler2 plugin

- src/skins-qt/menus.cc
This is a companion to https://github.com/audacious-media-player/audacious/pull/42 and dependent upon it
> Enable the menu item to Jump to a Song in QT5

- src/filewriter/filewriter.cc
- src/gtkui/ui_statusbar.cc
- src/moonstone/playlist_model.cc
- src/qtui/playlist_model.cc
- src/qtui/status_bar.cc
- src/skins-qt/main.cc
- src/skins/main.cc
This commit updates the unit formatting for bitrates to the universal
symbol from the now deprecated abbreviation.
> Fix bitrate unit formatting

- src/xsf/XSFFile.cc
This fixes the following deprecation warnings.
@jlindgren90: Could you please check if this compiles with older compilers? I think we still support GCC 4.7, right? Thanks.
```
../src/xsf/XSFFile.cc:54:28: warning: 'template<class _Arg, class _Result> struct std::unary_function' is deprecated [-Wdeprecated-declarations]
54 | struct IsWhitespace : std::unary_function<char, bool>
|                            ^~~~~~~~~~~~~~
In file included from /usr/include/c++/12.1.0/functional:49,
from ../src/xsf/XSFFile.cc:36:
/usr/include/c++/12.1.0/bits/stl_function.h:117:12: note: declared here
117 |     struct unary_function
|            ^~~~~~~~~~~~~~
../src/xsf/XSFFile.cc: In function 'std::string LeftTrimWhitespace(const std::string&)':
../src/xsf/XSFFile.cc:64:80: warning: 'constexpr …
```
> xsf: Fix compiler warnings

- src/ffaudio/ffaudio-core.cc
See also: https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff/548aeb93834b8425c86d
> ffaudio: Fix deprecation warnings with FFmpeg 5.1

- configure.ac
- src/config.h.meson
- src/oss4/meson.build
- src/oss4/oss.h
OpenBSD has not used OSS for ages so stop checking for the soundcard.h header outside of sys/.
> oss: Cleanup header handling

- .github/actions/install-dependencies/install-dependencies.sh
- src/oss4/oss.cc
- src/playlist-manager-qt/playlist-manager-qt.cc
- src/qtui/playlist-qt.cc
- src/skins-qt/drag-handle.cc
- src/skins-qt/eq-graph.cc
- src/skins-qt/eq-slider.cc
- src/skins-qt/equalizer.cc
- src/skins-qt/hslider.cc
- src/skins-qt/main.cc
- src/skins-qt/menurow.cc
- src/skins-qt/playlist-slider.cc
- src/skins-qt/playlist-widget.cc
- src/skins-qt/playlistwin.cc
- src/skins-qt/window.cc
- src/skins/eq-graph.cc
- src/ui-common/qt-compat.h
For now it is sufficient to share this header internally.
In the future we may move it into libaudqt.
> Fix Qt 6 deprecation warnings with a compatibility layer

- configure.ac
- src/sid/xmms-sid.cc
- src/sid/xs_sidplay2.cc
Ref https://www.hvsc.c64.org/download/C64Music/DOCUMENTS/Songlengths.faq
HVSC 68 introduced new songlengths db format.
Since HVSC 71 the old format db is no longer included.
`SidDatabase::length()` apparently assumes old db format while `SidDatabase::lengthMs()` works with new format, so switch to using that.
See: https://github.com/libsidplayfp/sidplayfp/blob/d241d27938b0f1f9f8a10d172eab1073868728fd/src/player.cpp#L597
Also:
* fix ROM file and the songlength db search path, which was broken due to missing / at least when using custom install prefix with Meson build
* require libsidplayfp >= 2.0 also with autotools build (Meson build already requires it), since the new db format is only supported with version >= 2.0.0
> Support new songlengths db format in SID plugin 

- src/ffaudio/ffaudio-core.cc
FFmpeg logs warnings as below when opening files if the packet timebase is not set. This affects for example WebM files downloaded from YouTube with yt-dlp.
These warnings are particularly distracting in the Qt interface where we show them in the status bar.
WARNING ../src/ffaudio/ffaudio-core.cc:201 [opus]: <0x7f849812ae40> Could not update timestamps for skipped samples.
See also:
- https://github.com/FFmpeg/FFmpeg/commit/889bc79b5f5cef757be3b23dd44c9908fc08330e
- https://github.com/aubio/aubio/issues/236
- https://www.itcodet.com/cpp/cpp-av_codec_set_pkt_timebase-function-examples.html
> ffaudio: Prevent warning about discarded samples

- src/amidiplug/i_fileinfo.cc
- src/delete-files/delete-files.cc
- src/gtkui/layout.cc
- src/gtkui/ui_gtk.cc
- src/hotkey/gui.cc
- src/qtui/main_window.cc
- src/skins-qt/equalizer.cc
- src/skins-qt/main.cc
- src/skins-qt/playlistwin.cc
- src/skins-qt/plugin-window.cc
- src/skins-qt/search-select.cc
- src/skins/equalizer.cc
- src/skins/main.cc
- src/skins/playlistwin.cc
- src/skins/plugin-window.cc
- src/skins/window.cc
- src/skins/window.h
- src/ui-common/dialogs-qt.cc
With window managers like icewm and i3 users can configure window specific settings. For this to work toplevel windows must be distinguishable by a X11 property. Because Audacious uses the same WM_CLASS property for all its windows, the WM_WINDOW_ROLE property must be set. However, Audacious currently does not set this property. It is defined in the ICCCM manual for X11 clients. This patch sets this property on Gtk and Qt toplevel windows using designated library calls.
> Add a WM_WINDOW_ROLE property to toplevel X11 windows.

- meson.build
- src/config.h.meson
Depends on https://github.com/audacious-media-player/audacious/pull/62 to include `-lintl` in audacious.pc, required for BSD, macOS and Windows.
> meson: Use cross platform approach to search and link libintl

- src/psf/eng_psf2.cc
- src/psf/psx.cc
- src/psf/psx_hw.cc
sprintf/vsprintf are deprecated since macOS 13.
> psf: Use snprintf instead of insecure sprintf

- meson.build
CYGWIN uses shared libraries with `.dll` extension like Windows.
This patch fixes `meson.build` for setting `PLUGIN_SUFFIX` to the correct value for this platform.
> CYGWIN: meson: support correct file extension for plugins.

- meson.build
- src/meson.build
Waveout driver can be compiled without troubles on CYGWIN.
This fix allows to use the player without using SDL or PortAudio, if the user wants.
> CYGWIN: meson: include waveout driver to plugins

- src/statusicon-qt/statusicon.cc
Even though we override the QSystemTrayIcon::event() method,
it is never called by Qt (at least on Linux when the panel/DE
supports StatusNotifierItem). Therefore our custom info popup
is not shown. Set a proper tooltip as workaround.
> statusicon-qt: Set proper tooltip

- configure.ac
- src/lyricwiki-qt/lyricwiki.cc
lyricwiki-qt: Add support for chartlyrics.com. Closes: #1217
lyrics.ovh has been unreliable in the past months.
Meanwhile it is working again but still has issues at times.
Offer chartlyrics.com as an alternative. It is also not perfect
with no support for HTTPS and lyrics for new songs are missing.
Hoever having a choice is still better. And it is free for
non-commercial use, unlike many other sites.
See also:
- http://www.chartlyrics.com/api.aspx (Terms of Use)
- https://github.com/NTag/lyrics.ovh/issues/15
- https://github.com/NTag/lyrics.ovh/issues/17
> lyricwiki-qt: Add support for chartlyrics.com. Closes: #1217

- .github/actions/install-dependencies/action.yml
- .github/workflows/c-cpp.yml
See also: https://www.msys2.org/news/#2023-12-13-starting-to-drop-some-32-bit-packages
> CI: Use 64-bit for Windows and disable autotools build

- src/lyrics-common/lyrics_ovh_provider.cc
https://lyrics.ovh embeds a French prefix for `Lyrics of the song {title} by {artist}` to all lyrics,
regardless of the lyrics language or user country (verified with proxies).
Examples:
- https://api.lyrics.ovh/v1/R.E.M./Shiny%20Happy%20People
- https://api.lyrics.ovh/v1/R.E.M./At%20My%20Most%20Beautiful
Questions:
- Is it safe to return the char pointer like this or should it be wrapped into a String or StringBuf?
- Is there a way to trim also non-breaking-space characters? `g_strchug()` does not remove them.
The 2nd example shows therefore unnecessary newlines below the header.
> lyrics: Remove French prefix which lyrics.ovh embeds into lyrics

- .github/actions/install-dependencies/action.yml
- .github/actions/install-dependencies/install-dependencies.sh
- .github/actions/run-action/run-action.sh
- meson.build
- meson_options.txt
- src/qtaudio/meson.build
- src/qtglspectrum/meson.build
- src/qthotkey/meson.build
- src/streamtuner/meson.build
Qt 5 is no longer supported upstream and KDE has migrated as well.
Note that our Autotools build does not support Qt 6.
See also: https://doc.qt.io/qt-6/supported-platforms.html#supported-qt-versions
> meson: Change default Qt version to 6

- src/scrobbler2/config_window.cc
- src/scrobbler2/scrobbler.cc
- src/scrobbler2/scrobbler.h
The GLib mainloop and timers don't run here when using Qt.
Make use of QueuedFunc from libaudcore to fix this.
See also: https://github.com/orgs/audacious-media-player/discussions/111
> scrobbler2: Make plugin work on macOS (and potentially Windows too)

- src/blur_scope-qt/blur_scope.cc
The include path given as glib-2.0/glib.h is not correct for meson/pkg-config. This usually works on systems where glib-2.0 is in a system include path, but will break when this is not the case. Changed to match other modules.
> blur_scope-qt: fix incorrect glib.h include path

- src/gtkui/ui_gtk.cc
- src/gtkui/ui_infoarea.cc
- src/skins-qt/plugin.cc
- src/skins/plugin.cc
Fixes for Audacious when running on Wayland, see the commit messages for more details.
Tested with `QT_QPA_PLATFORM=wayland audacious` and `GDK_BACKEND=wayland audacious --gtk` on Ubuntu 24.04.
> Wayland fixes

- src/gtkui/gtkui.h
- src/gtkui/ui_gtk.cc
- src/gtkui/ui_playlist_widget.cc
- src/skins/main.cc
- src/skins/playlist-widget.cc
Follow-up for the infopopup changes in libaudgui from https://github.com/audacious-media-player/audacious/pull/1399.
> Set parent window for infopopup

- .github/actions/install-dependencies/install-dependencies.sh
The last usage of dbus-glib has been removed in https://github.com/audacious-media-player/audacious-plugins/commit/3dc8222f59bc8a2352fc0bac54e34a22adc6e122
> CI: remove dbus-glib dependency

- src/mpris2/plugin.cc
*This PR adds more MPRIS2 metadata to broadcast about the current track to "MPRIS2 Server" plugin.*
---
Compared to players like [Supersonic](https://github.com/dweymouth/supersonic/blob/3f304483834d37f1c5f3c75da414ff032e6b6dbe/backend/mpris.go#L276), [Rhythmbox](https://github.com/GNOME/rhythmbox/blob/49d903bf2b01aaebc7bae5aad1494d4abe28f116/plugins/mpris/rb-mpris-plugin.c#L546), [DeaDBeeF](https://github.com/DeaDBeeF-Player/deadbeef-mpris2-plugin/blob/fdfd00119db5128165170fb5738d60b47acdc3fb/src/mprisServer.c#L141) (via plugin) or Spotify, Audacious does not provide much metadata about the currently playing track.
<details>
<summary><i>Intercepted Examples (using dbus-python)</i></summary>
\
**Audacious:** (7)
```json
{
"xesam:title": "apple_pie.0",
"xesam:artist": [ "NǽnøĉÿbbŒrğ …
```
> mpris2: send more metadata about current track

- .github/actions/install-dependencies/action.yml
UCRT64 is meanwhile the recommended MSYS2 environment for Windows.
Visual Studio uses it by default since 2015.
See also:
- https://www.msys2.org/docs/environments/
- https://www.msys2.org/news/#2022-10-29-changing-the-default-environment-from-mingw64-to-ucrt6
> CI: Switch from MINGW64 to UCRT64

- src/pulse/pulse_audio.cc
Give the PulseAudio audio output plugin higher priority to that of PipeWire's. Under a PulseAudio setup, the PipeWire output may be selected by default, which would promptly fail to work, as there is no PipeWire server/proxy running.
On the other hand, under a PipeWire setup, PulseAudio output would still work normally, as pipewire-pulse acts as a PulseAudio server.
Making PulseAudio the top preference allows for better compatibility for different setups, especially for distributions that have not (yet) switched to PipeWire as the default audio server.
> fix(pulse): give PulseAudio output plugin higher priority than PipeWire

- src/gtkui/ui_infoarea.cc
Fading out text with emoji characters can lead to them still being displayed above the text of a new track.
Ignoring zero alpha channels avoids this.
Reproduced on Ubuntu 24.04. Arch Linux requires "noto-fonts-emoji".
> gtkui: Hide info area text containing emoji properly. Closes: #1491

- src/sid/xs_sidplay2.cc
See also: https://github.com/libsidplayfp/libsidplayfp/releases/tag/v2.10.0
> sid: Fix deprecation warning

- src/opus/opus.cc
Re-added Thomas's original RG code and some logic to support both R128 and RG, while preferring R128.
> opus: add support for RG tags again

- src/qtui/main_window.cc
If the status icon plugin is used with close to system tray the UI main window is closed. On Mac OS there is not an easy way to make it reappear. The system tray activation trigger is disabled on Mac OS. This is for good reason due to one button mouse support and that this usually is intended to open the status/tray menu. Instead we can handle the application state change activate signal which will fire when the dock icon is clicked.
> Make UI appear on Qt::ApplicationActive for MacOS

- src/qtui/main_window.cc
This reverts commit 2f2d5374f0f8ec7f453e37d821f2687a5a36dc25 from #174 
Better to handle this in libaudqt directly on the QApplication so that it is main window/skin agnostic.
See audacious-media-player/audacious#1523.
> Revert "qtui: Make UI appear on Qt::ApplicationActive for macOS"

- configure.ac
- src/pipewire/meson.build
- src/pipewire/pipewire.cc
- Use RingBuf from audcore
- Respect output_buffer_size setting
- Improve get_delay() and drain() functions
- Add support for 5 and 7 channels
> pipewire: Revise plugin code. Closes: #1401

- src/pipewire/pipewire.cc
This makes Audacious again work "out of the box" on systems without pipewire installed/running.
@radioactiveman Can you check that this doesn't break systems that *do* have pipewire available?
> pipewire: fall back to other output plugins if not available

- src/mpris2/plugin.cc
I updated the packages of audacious and audacious-plugins to 4.4.2 but I got a tiny error at compile time with mpris2 plugin.
This was the message printed on the console:
```
../src/mpris2/plugin.cc: In function ‘void add_g_variant_str(const char*, const char*, Index<_GVariant*>&)’: ../src/mpris2/plugin.cc:112:24: error: ‘strlen’ was not declared in this scope
112 |     if (! value_str || strlen (value_str) == 0)
|                        ^~~~~~
../src/mpris2/plugin.cc:35:1: note: ‘strlen’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
34 | #include "object-player.h"
+++ |+#include <cstring>
35 |
```
I did the suggestion from GCC and I added `string.h` near the other include files: after that, the build process completed successfully.
No other corrections were …
> mpris2: fix build on CYGWIN

- src/sid/xmms-sid.cc
Support the official MIME type for SID module files. It has replaced the inofficial audio/x-psid and audio/x-sidtune types.
> Add MIME type audio/prs.sid
